# Generated by Django 5.0.6 on 2024-07-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование актива')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='Описание актива')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.entitytype', verbose_name='Тип актива')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование шаблона актива')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание шаблона актива')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.entitytype', verbose_name='Тип актива')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование связи')),
                ('relation_type', models.CharField(choices=[('applies', 'Отностится'), ('depends', 'Зависит'), ('consists', 'Состоит'), ('parent', 'Родитель'), ('subsidiary', 'Дочерний'), ('part', 'Часть')], max_length=50, verbose_name='Тип связи')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='Описание связи')),
                ('direction', models.CharField(choices=[('left_to_right', 'Слева на право'), ('right_to_left', 'Справа на лево'), ('both', 'В обе стороны'), ('none', 'Без направления')], max_length=50, verbose_name='Направление связи')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательный для ввода')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_asset', to='asset.asset', verbose_name='Левый актив')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_asset', to='asset.asset', verbose_name='Правый актив')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.entitytype', verbose_name='Тип актива')),
            ],
        ),
        migrations.CreateModel(
            name='RelationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование шаблона связи')),
                ('relation_type', models.CharField(choices=[('applies', 'Отностится'), ('depends', 'Зависит'), ('consists', 'Состоит'), ('parent', 'Родитель'), ('subsidiary', 'Дочерний'), ('part', 'Часть')], max_length=50, verbose_name='Тип связи')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание шаблона связи')),
                ('direction', models.CharField(choices=[('left_to_right', 'Слева на право'), ('right_to_left', 'Справа на лево'), ('both', 'В обе стороны'), ('none', 'Без направления')], default='none', max_length=50, verbose_name='Направление связи')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательный для ввода')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.entitytype', verbose_name='Тип актива')),
            ],
        ),
    ]
