# Generated by Django 5.0.6 on 2024-07-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование шаблона аттрибута')),
                ('attribute_type', models.CharField(choices=[('integer', 'Целое число'), ('string', 'Строка'), ('boolean', 'Булевый тип'), ('list', 'Список')], max_length=50, verbose_name='Тип аттрибута')),
                ('is_dictionary', models.BooleanField(default=False, verbose_name='Словарь')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание шаблона аттрибута')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательный для ввода')),
            ],
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('asset', 'Активы'), ('relation', 'Связи'), ('task', 'Задачи')], max_length=50, verbose_name='Тип сущности')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование типа актива')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание типа актива')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование значения')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Описание значения')),
                ('attribute_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.dictionaryattribute', verbose_name='Шаблон аттрибута')),
            ],
        ),
        migrations.AddField(
            model_name='dictionaryattribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.entitytype', verbose_name='Тип актива'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField(verbose_name='Идентификатор актива')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование аттрибута')),
                ('attribute_type', models.CharField(choices=[('integer', 'Целое число'), ('string', 'Строка'), ('boolean', 'Булевый тип'), ('list', 'Список')], max_length=50, verbose_name='Тип аттрибута')),
                ('value', models.BinaryField(blank=True, null=True, verbose_name='Значение аттрибута')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='Комментарий аттрибута')),
                ('required', models.BooleanField(verbose_name='Обязательный для ввода')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.entitytype', verbose_name='Тип актива')),
            ],
        ),
    ]
